services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    restart: always
    ports:
      - 5432:5432
    env_file: .env
  app:
    image: xdigital
    ports:
      - 4000:4000
